### ISSUE TITLE
chat_info_screen.dart

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/flutter-samples#10]
Hi 

In chat_info_screen.dart

`body: StreamBuilder<List<Channel>>(
        stream: chat.client.queryChannels(`

lib/group/chat_info_screen.dart:449:29: Error: The argument type 'Future<List<Channel>>' can't be assigned to the parameter type 'Stream<List<Channel>>'.
 - 'Future' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'Channel' is from 'package:stream_chat/src/api/channel.dart' ('/Volumes/usb/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat-1.0.3-beta/lib/src/api/channel.dart').
 - 'Stream' is from 'dart:async'.
        stream: chat.client.queryChannels(

**Comment by Abacaxi-Nelson** [comment]
Can replace it with a futureBuilder... but it will not update itself...

**Comment by imtoori** [comment]
are you sure you're using the latest version?
we changed it to return a stream in the latest one

**Comment by Abacaxi-Nelson** [comment]
hi @imtoori 
nice catch, 
i was using stream_chat_flutter: **^1.0.1-beta**
will update :)
