### ISSUE TITLE
Use case: send FCM notifications

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/flutter-samples#12]
Hi,
I'm using webhooks, to send notifications on **_message.new_**.
Everything is working. 
But to send 'Unsername send a new message on Group XX' where XX is the group name.. but channel name is not sent from webhook.

Can you confirm ?

Thank you,
Nelson

**Comment by Abacaxi-Nelson** [comment]
i finally store on my db, map of channel_id and his name.

**Comment by SeniYG** [comment]
Hi there,

Sorry for the delay. Indeed, the channel data isn't returned with the message in **message.new** events.
Storing this information on your side might be the best option here.

Best,
