### ISSUE TITLE
[Why] updating user from backend, duplicate user ?

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/flutter-samples#20]
Hi all;

im updating username from backend :
```js
const update = {
  id: newValue['uid'],
  set: { name: newValue['username'], },
};

const clientGetStream = StreamChat.getInstance('CC', 'XX');
const response = await clientGetStream.partialUpdateUser(update);
console.log('response update username ', JSON.stringify(response));
```

but when searching, user nelson appear twice :
![image](https://user-images.githubusercontent.com/556990/110540855-4833e400-8127-11eb-9e69-5466446c3628.png)

In dashboard, ID is unique with correct username

Is there some cache not updated ?
thanks,

**Comment by imtoori** [comment]
Hey
Can I ask you to contact [support](https://getstream.io/contact/support/) for issues not related to the flutter sdk? 
I'm sure they can help you better

**Comment by Abacaxi-Nelson** [comment]
Sure !
Thank you @imtoori
