### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by ritam749** [GetStream/flutter-samples#36]
Hello Stream team,
I really like all the sample apps, but I just want ask that is it possible if you can give us a comprehensive guide or a video on how to setup the projects or sample apps. By that i mean if you can help me add my own firebase console project. What all do i need to enable and where to add my stream api key and secret key.Could you please reply as i want to improve upon the first stream chat v1 sample app and after improving it give it us a college project. So could you pease relpy fast. THANK YOU!

**Comment by sachaarbonel** [comment]
Hey @ritam749 this video series might help get you up to speed setting up Firebase and Stream Chat, check it out: https://www.youtube.com/watch?v=H7FjCWHmP9Y

**Comment by ritam749** [comment]
I have watched he video but I do not know what to enable in firebase for the 1st sample app(stream_chat_v1) and 3rd sample app(Imessage clone).Please help by making a vid or readme or just comment some detailed steps. Please reply

**Comment by imtoori** [comment]
@ritam749 can you elaborate more? there is no firebase implementation in the two sample apps you pointed out

**Comment by ritam749** [comment]
Ok sorry i thought there was a googleservices.json. Then could you tell me where to add the api keys in the two apps

**Comment by imtoori** [comment]
https://github.com/GetStream/flutter-samples/blob/main/packages/stream_chat_v1/lib/app_config.dart

this is the file for stream_chat_v1

https://github.com/GetStream/flutter-samples/blob/main/packages/imessage/lib/main.dart

this is for the imessage clone

**Comment by ritam749** [comment]
And another question, I am getting an error for the second package;
`/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter-1.3.0-beta/lib/src/channel_file_display_screen.dart:146:48: Error: The method 'loadMore' isn't defined for the class 'MessageSearchBlocState'.
 - 'MessageSearchBlocState' is from 'package:stream_chat_flutter_core/src/message_search_bloc.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter_core-1.5.3/lib/src/message_search_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'loadMore'.
          onEndOfPage: () => messageSearchBloc.loadMore(
                                               ^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter-1.3.0-beta/lib/src/channel_media_display_screen.dart:169:48: Error: The method 'loadMore' isn't defined for the class 'MessageSearchBlocState'.
 - 'MessageSearchBlocState' is from 'package:stream_chat_flutter_core/src/message_search_bloc.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter_core-1.5.3/lib/src/message_search_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'loadMore'.
          onEndOfPage: () => messageSearchBloc.loadMore(
                                               ^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 42s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       344.4s
Exception: Gradle task assembleDebug failed with exit code 1`


Please tell me how to resolve
