### ISSUE TITLE
Package 2(Chatty) setup help

### ISSUE THREAD

**Issue by ritam749** [GetStream/flutter-samples#37]
When i try "flutter run" on chatty i get the following errors:

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter-1.3.0-beta/lib/src/channel_file_display_screen.dart:146:48: Error: The method 'loadMore' isn't defined for the class 'MessageSearchBlocState'.
 - 'MessageSearchBlocState' is from 'package:stream_chat_flutter_core/src/message_search_bloc.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter_core-1.5.3/lib/src/message_search_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'loadMore'.
          onEndOfPage: () => messageSearchBloc.loadMore(
                                               ^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter-1.3.0-beta/lib/src/channel_media_display_screen.dart:169:48: Error: The method 'loadMore' isn't defined for the class 'MessageSearchBlocState'.
 - 'MessageSearchBlocState' is from 'package:stream_chat_flutter_core/src/message_search_bloc.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter_core-1.5.3/lib/src/message_search_bloc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'loadMore'.
          onEndOfPage: () => messageSearchBloc.loadMore(
                                               ^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 42s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       344.4s
Exception: Gradle task assembleDebug failed with exit code 1

Please resolve

**Comment by imtoori** [comment]
@ritam749 can you try the version that is in the `develop` branch?
it uses the nullsafety version of the sdk
