### ISSUE TITLE
Dependency hell for stream_chat_v1 project

### ISSUE THREAD

**Issue by FahimLyn** [GetStream/flutter-samples#40]
`flutter pub get` fails to resolve versions because of version constraints in `pubspec.yaml`. I took at a stab at trying to manually resolve the versions but the rabbit hole goes too deep for me. The project is currently unusable.

**Comment by imtoori** [comment]
We're in the process of migrating to nullsafety and releasing a v2.0 of our package
You can try the new version in the develop branch
