### ISSUE TITLE
PUB GET not working stream chat persistence

### ISSUE THREAD

**Issue by mortezaking0151** [GetStream/flutter-samples#5]
hi I add dart and flutter when I wanna use put get I will get this error

> Because stream_chat_persistence >=1.0.2-beta depends on stream_chat ^1.0.3-beta which depends on meta ^1.2.4, stream_chat_persistence >=1.0.2-beta requires meta ^1.2.4.
And because every version of flutter from sdk depends on meta 1.1.8, stream_chat_persistence >=1.0.2-beta is incompatible with flutter from sdk.
So, because example depends on both flutter any from sdk and stream_chat_persistence ^1.0.2-beta, version solving failed.
pub get failed (1; So, because example depends on both flutter any from sdk and stream_chat_persistence ^1.0.2-beta, version solving failed.)

this stream_chat_persistence have a problem when I remove this from package list pub get work perfectly
pls help me
sorry for my poor English
thanks

**Comment by xsahil03x** [comment]
Hey @mortezaking0151, can you try upgrading your flutter SDK? Also, it would be more helpful if you can provide the package versions you are currently using.

**Comment by mortezaking0151** [comment]
> Hey @mortezaking0151, can you try upgrading your flutter SDK? Also, it would be more helpful if you can provide the package versions you are currently using.

hi i use last version of flutter 
and i use "any" so thats use last one i think 
and i change version to 1.0.2 beta and its work but i get more errors about that i must downgrade flutter version

**Comment by xsahil03x** [comment]
Okay, so the simplest solution you can do is to override the meta dependency in your project.
```dart
dependency_overrides:
  meta: '1.1.8'
```

**Comment by mortezaking0151** [comment]
> Okay, so the simplest solution you can do is to override the meta dependency in your project pubspec.
> 
> ```dart
> 
> dependency_overrides:
> 
>   meta: '1.1.8'
> 
> ```

okey bro thanks♥️
