### ISSUE TITLE
IMessage can't run in android emulator

### ISSUE THREAD

**Issue by noChamp** [GetStream/flutter-samples#52]
hi

I am using flutter 2.2.3, and JDK 16 and I get this in the console when running imessage:

The following assertion was thrown during layout:
A RenderFlex overflowed by 0.273 pixels on the right.

The relevant error-causing widget was
    Row 
lib\channel_preview.dart:65

can you help?
thanks

**Comment by imtoori** [comment]
hi
we updated the example and now it's working fine 
sorry for the delay
