### ISSUE TITLE
new direct messages bug

### ISSUE THREAD

**Issue by yeahs2000** [GetStream/flutter-samples#58]

**Comment by imtoori** [comment]
can you elaborate more?

**Comment by yeahs2000** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MessageInput(dirty, dependencies: [StreamChatTheme, _LocalizationsScope-[GlobalKey#29850]], state: MessageInputState#a52ab):
Channel null is not yet initialized
'package:stream_chat_flutter/src/user_mentions_overlay.dart':
Failed assertion: line 29 pos 11: 'channel.state != null'

The relevant error-causing widget was: 
  MessageInput MessageInput:file:///Users/yejianhui/workspace/snail/snail_client/lib/pages/home/new_chat_screen.dart:391:19
When the exception was thrown, this was the stack: 
#2      new UserMentionsOverlay (package:stream_chat_flutter/src/user_mentions_overlay.dart:29:11)
#3      MessageInputState._buildMentionsOverlayEntry (package:stream_chat_flutter/src/message_input.dart:1191:12)

**Comment by papirovdavid** [comment]
Hi,
I currently have it happens every time

**Comment by papirovdavid** [comment]
Have downloaded the latest master version from GitHub:
![image](https://user-images.githubusercontent.com/3015069/143448443-086d047b-bccf-4032-bb1f-5489d031bdb1.png)

**Comment by papirovdavid** [comment]
Running, choosing the first user, click on New Chat button on the top,
Then tap into the write message bar, and getting the crash

**Comment by papirovdavid** [comment]
![image](https://user-images.githubusercontent.com/3015069/143448770-65225c13-67ae-49e7-9dbc-0488f71423dc.png)
![image](https://user-images.githubusercontent.com/3015069/143448836-c01f7515-db76-4b9d-97fe-ce4c4e331684.png)

**Comment by imtoori** [comment]
this has been fixed in the latest 3.3.0
