### ISSUE TITLE
Message Forward

### ISSUE THREAD

**Issue by 1AhmedYasser** [GetStream/flutter-samples#61]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

No

### Describe the solution that you'd like

I Want to able to forward a message or multiple messages to other users or channels in the app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Michaelbenchetrit91** [comment]
> @Michaelbenchetrit91 there's no documentation on that, it's just a normal send message call. Let me try writing a little snippet for you

Hi imtoori would really appreciate to get the snippet, thank you!

**Comment by xsahil03x** [comment]
Hey @Michaelbenchetrit91,

 @imtoori recently got covid positive, I'm here with the snippet for you.
 
 ```dart
 void onForwardTap(Message message) {
  // Navigate to the channel selection screen.
  Navigator.of(context).pushNamed(
    'ForwardSelectionScreen',
    arguments: message,
  );
}

class ForwardSelectionScreen extends StatelessWidget {
  const ForwardSelectionScreen({
    Key? key,
    required this.messageToForward,
  }) : super(key: key);

  final Message messageToForward;

  void onChannelTap(Channel channel) async {
    // Add additional data to identify the message as forwarded.
    final message = messageToForward.copyWith(
      extraData: {
        ...messageToForward.extraData,
        'isMessageForwarded': true,
        // TODO: Add additional details about the forwarded message.
      },
    );

    // Initialize channel if not yet initialized.
    if (channel.state == null) await channel.watch();

    // Send message to the channel.
    channel.sendMessage(message);

    // Navigate to the chat screen.
    Navigator.of(context).pushNamed(
      'ChannelPage',
      arguments: channel,
    );
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
            // ... channels,
        );
  }
}
 ```
 
 Additionally, you can also modify the message item look in the `MessageListView` to show it as a forwarded message.
 
 Thanks,
 Sahil

**Comment by Michaelbenchetrit91** [comment]
Thank you very much @1AhmedYasser 
@imtoori My sincere wishes for a swift recovery
