### ISSUE TITLE
Failed when build app

### ISSUE THREAD

**Issue by machudat18** [GetStream/flutter-samples#7]
![image](https://user-images.githubusercontent.com/56917449/108822447-ad4ced00-75f1-11eb-8eef-1226412529ff.png)
I just build app today and get this error . Can any one help me pls

**Comment by imtoori** [comment]
can you try one of these solutions? https://stackoverflow.com/questions/60404457/no-version-of-ndk-matched-the-requested-version
This is related to your local environment
