### ISSUE TITLE
Can't connect with server GetStream by my API Key

### ISSUE THREAD

**Issue by duy1998** [GetStream/flutter-samples#70]
I received the message.
Unhandled Exception: WebSocketError(message: JWTAuth error: signature is not valid. Make sure the token is created using the secret for API key "bwkw956c3c4s", data: ErrorResponse(code: 43, message: JWTAuth error: signature is not valid. Make sure the token is created using the secret for API key "bwkw956c3c4s", statusCode: 401, moreInfo: ))

Anyone can help me ?

**Comment by imtoori** [comment]
Apparently, the JWT was not created correctly 
Please take a look at [this](https://getstream.io/chat/docs/flutter-dart/tokens_and_authentication/?language=dart) and [this](https://getstream.io/chat/docs/flutter-dart/tokens_and_authentication/?language=dart#manually-generating-tokens).
I'll close this one, feel free to reopen it if needed

**Comment by duy1998** [comment]
I got it.
Thank you
