### ISSUE TITLE
Thread Reply doesn't work in Flutter Sample App as it supposed to be.

### ISSUE THREAD

**Issue by bhanu-under25** [GetStream/flutter-samples#75]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

latest version

### What happened?

Thread replies doesn't work in the Flutter Sample App which downloaded from [https://getstream.io/downloads/flutter-sample-app.apk](https://getstream.io/downloads/flutter-sample-app.apk)

### Steps to reproduce

```bash
1. Go to any test channel
2. long press on a message
3. Select thread reply
4. First it prefill the text field with the parent message and it doesn't add thread reply
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
just fixed in develop
