### ISSUE TITLE
No signature when building Chatty application

### ISSUE THREAD

**Issue by BrianMwas** [GetStream/flutter-samples#76]
I have run all the necessary commands to get started and even shifted it to the new embedding system but it still does not run. It gives off this error
 What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_9ciku1zpbujrrz24comy0tc8b.android() is applicable for argument types: (build_9ciku1zpbujrrz24comy0tc8b$_run_closure2) values: [build_9ciku1zpbujrrz24comy0tc8b$_run_closure2@6ed2056c]

**Comment by imtoori** [comment]
Hi @BrianMwas 
as you can see in the [Readme](https://github.com/GetStream/flutter-samples#-historic-projects) the project is not actively maintained. They were developed using older versions of our packages and Flutter.
