### ISSUE TITLE
Project doesn't compile

### ISSUE THREAD

**Issue by cliffofdeath** [GetStream/flutter-samples#8]
The current version of the sample project doesn't compile (commit a22b31d2aba1e788ce7f142eb38cd4e9c819c466)

Following build errors occur:

lib/main.dart:348:23: Error: The argument type 'LayoutBuilder Function(BuildContext, dynamic)' can't be assigned to the parameter type 'Widget Function(BuildContext)'.
 - 'LayoutBuilder' is from 'package:flutter/src/widgets/layout_builder.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/layout_builder.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
        emptyBuilder: (_, __) {
                      ^
lib/main.dart:495:39: Error: The argument type 'LayoutBuilder Function(BuildContext, dynamic)' can't be assigned to the parameter type 'Widget Function(BuildContext)'.
 - 'LayoutBuilder' is from 'package:flutter/src/widgets/layout_builder.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/layout_builder.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
                        emptyBuilder: (_, query) {

**Comment by Abacaxi-Nelson** [comment]
just replace emptyBuilder: (_) to  emptyBuilder: (context, data) {

**Comment by imtoori** [comment]
Hi!
Are you using the stable channel of flutter?

**Comment by cliffofdeath** [comment]
Yes I do, I'm using version 1.22.6.

**Comment by Abacaxi-Nelson** [comment]
@cliffofdeath and : `stream_chat_flutter: ^1.3.2-beta`?

**Comment by cliffofdeath** [comment]
No, ^1.0.2-beta is used in your example project.

**Comment by imtoori** [comment]
@cliffofdeath it's working fine for me
do you still see this issue?
